"""First postgres revision

Revision ID: 73bf4bab9126
Revises: 
Create Date: 2022-10-18 17:32:51.913648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bf4bab9126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Book_id', table_name='Book')
    op.drop_table('Book')
    op.drop_index('ix_Authors_id', table_name='Authors')
    op.drop_table('Authors')
    op.drop_index('ix_blogs_id', table_name='blogs')
    op.drop_table('blogs')
    op.drop_index('ix_Users_id', table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='blogs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blogs_pkey')
    )
    op.create_index('ix_blogs_id', 'blogs', ['id'], unique=False)
    op.create_table('Authors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Authors_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Authors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_Authors_id', 'Authors', ['id'], unique=False)
    op.create_table('Book',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Book_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Authors.id'], name='Book_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Book_pkey')
    )
    op.create_index('ix_Book_id', 'Book', ['id'], unique=False)
    # ### end Alembic commands ###
