version: '3.8'
services:
    app:
        build: .
        command: uvicorn postgres_blog.main:app 
        ports:
            - "8000:8000"
    
    postgres:
        image: postgres:13-alpine
        container_name: db-postgres
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        restart: unless-stopped        
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            
volumes:
    pgdata:
        driver: local